basePath: /v1
definitions:
  models.DiscoveryData:
    properties:
      BrandName:
        description: Brand Name
        type: string
      FirmwareVersion:
        description: Firmware Version
        type: string
      MachineModel:
        description: Machine Model
        type: string
      MachineName:
        description: Machine Name
        type: string
      MainboardID:
        description: Motherboard ID (16-bit)
        type: string
      MainboardIP:
        description: Motherboard IP Address
        type: string
      ProtocolVersion:
        description: Protocol Version
        type: string
    type: object
  models.DiscoveryResponse:
    properties:
      discovered:
        items:
          $ref: '#/definitions/models.DiscoveryData'
        type: array
    type: object
  models.HealthResponse:
    type: object
  models.StatusRefreshRequest:
    properties:
      machine_id:
        type: string
      machine_ip:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Flux, V1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Flux API V1
  version: "1.0"
paths:
  /discovery:
    post:
      consumes:
      - application/json
      description: Discovers new Printers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DiscoveryResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - discovery
  /health:
    get:
      consumes:
      - application/json
      description: Returns the health and status of the various services that make
        up the API.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - health
  /status:
    post:
      consumes:
      - application/json
      description: Refreshes the status of a machine
      parameters:
      - description: Status Refresh Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.StatusRefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - discovery
schemes:
- https
swagger: "2.0"
